// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const userDelete = `-- name: UserDelete :one
delete from users where id = $1 returning id
`

func (q *Queries) UserDelete(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, userDelete, id)
	err := row.Scan(&id)
	return id, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
select id, username, email, password, created_at, updated_at from users where email = $1 limit 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one
select id, username, email, password, created_at, updated_at from users where id = $1 limit 1
`

func (q *Queries) UserGetByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
select id, username, email, password, created_at, updated_at from users where username = $1 limit 1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userInsert = `-- name: UserInsert :one
insert into users
    ( username, email, password, created_at, updated_at )
values
    ( $1, $2, $3, $4, $5 )
returning username
`

type UserInsertParams struct {
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) (string, error) {
	row := q.db.QueryRowContext(ctx, userInsert,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var username string
	err := row.Scan(&username)
	return username, err
}

const userUpdate = `-- name: UserUpdate :one
update users set
    username = $1, email = $2, created_at = $3, updated_at = $4
where id = $5
returning id, username, email, password, created_at, updated_at
`

type UserUpdateParams struct {
	Username  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ID        int32
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userUpdate,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
